In [2]:
import pandas as pd
import sys
import nbformat
import numpy as np
import plotly.express as px

### Carregando o DataFrame ###

In [3]:
file_path = 'social_media_mental_health.csv'

df = pd.read_csv(file_path)
df.head()

,User_ID,Age,Gender,User_Archetype,Primary_Platform,Daily_Screen_Time_Hours,Dominant_Content_Type,Activity_Type,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,GAD_7_Severity,PHQ_9_Score,PHQ_9_Severity
0,U-b23639d2,18,Male,Hyper-Connected,Twitter/X,8.50,Gaming,Active,0,0,3.9,9,Mild,5,Mild
1,U-e7778765,20,Male,Digital Minimalist,TikTok,0.50,Gaming,Active,0,0,5.5,0,Minimal,8,Mild
2,U-76749892,18,Female,Digital Minimalist,Snapchat,0.91,Gaming,Active,0,0,8.9,1,Minimal,3,None-Minimal
3,U-dcbbd7f9,18,Female,Hyper-Connected,Snapchat,7.43,Gaming,Active,1,0,6.2,13,Moderate,0,None-Minimal
4,U-9e1ba278,18,Male,Hyper-Connected,LinkedIn,4.94,Entertainment/Comedy,Active,1,0,5.3,13,Moderate,10,Moderate

### Realizando a análise do DataFrame ###

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    8000 non-null   str
 1   Age                        8000 non-null   int64
 2   Gender                     8000 non-null   str
 3   User_Archetype             8000 non-null   str
 4   Primary_Platform           8000 non-null   str
 5   Daily_Screen_Time_Hours    8000 non-null   float64
 6   Dominant_Content_Type      8000 non-null   str
 7   Activity_Type              8000 non-null   str
 8   Late_Night_Usage           8000 non-null   int64
 9   Social_Comparison_Trigger  8000 non-null   int64
 10  Sleep_Duration_Hours       8000 non-null   float64
 11  GAD_7_Score                8000 non-null   int64
 12  GAD_7_Severity             8000 non-null   str
 13  PHQ_9_Score                8000 non-null   int64
 14  PHQ_9_Severity             8000 non-null   str
dtypes: float64(2), int64(5), str(8)
memory usage: 937.6 KB

In [5]:
df.describe()

,Age,Daily_Screen_Time_Hours,Late_Night_Usage,Social_Comparison_Trigger,Sleep_Duration_Hours,GAD_7_Score,PHQ_9_Score
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,19.057875,4.277210,0.379375,0.103125,5.803237,7.354250,5.380125
std,1.117892,2.310486,0.485262,0.304141,1.344054,4.633108,4.816641
min,18.000000,0.500000,0.000000,0.000000,3.000000,0.000000,0.000000
25%,18.000000,2.420000,0.000000,0.000000,4.800000,4.000000,1.000000
50%,19.000000,4.270000,0.000000,0.000000,5.800000,7.000000,5.000000
75%,20.000000,6.050000,1.000000,0.000000,6.800000,11.000000,9.000000
max,22.000000,11.310000,1.000000,1.000000,11.600000,21.000000,23.000000

### Análises de Ansiedade (GAD-7) ###

In [6]:
fig = px.histogram(df, x="GAD_7_Score", nbins=22, title="Distribuição do Score de Ansiedade (GAD-7)")
fig.show()

In [7]:
fig = px.histogram(df, x="GAD_7_Severity", 
                   category_orders={"GAD_7_Severity": ["Minimal", "Mild", "Moderate", "Severe"]},
                   title="Distribuição por Severidade de Ansiedade")
fig.show()

### Análises de Depressão (PHQ-9) ###

In [8]:
fig = px.histogram(df, x="PHQ_9_Score", nbins=22, title="Distribuição do Score de Depressão (PHQ-9)")
fig.show()

In [ ]:
fig = px.histogram(df, x="PHQ_9_Severity", 
                   category_orders={"PHQ_9_Severity": ["None-Minimal", "Mild", "Moderate", "Moderately Severe","Severe"]},
                   title="Distribuição por Severidade de Depressão")
fig.show()

In [11]:
import plotly.figure_factory as ff
import numpy as np

# Selecione apenas as colunas numéricas relevantes
cols = ['Daily_Screen_Time_Hours', 'Sleep_Duration_Hours', 
        'Late_Night_Usage', 'Social_Comparison_Trigger',
        'GAD_7_Score', 'PHQ_9_Score']

corr = df[cols].corr().round(2)

fig = ff.create_annotated_heatmap(
    z=corr.values,
    x=cols,
    y=cols,
    annotation_text=corr.values,
    colorscale='RdBu_r',
    showscale=True
)
fig.update_layout(title="Matriz de Correlação")
fig.show()

In [13]:
fig = px.scatter(df, x="Daily_Screen_Time_Hours", y="GAD_7_Score",
                 color="Activity_Type", opacity=0.5,
                 trendline="ols",
                 title="Tempo de Tela vs Ansiedade")
fig.show()